project:
  type: book
  output-dir: docs

book:
  title: "Centrality analysis on Rio Grande do Sul"
  author:
    - name: Ricardo Ruiz Sánchez
      orcid: 0009-0000-6108-3389
      email: ricardo.ruiz.sanchez@gmail.com
      role:
       - kWritingOrigina
       - Methodology
       - Software
       - Validation
       - Formal analysis
       - Investigation
       - Resources
       - Data Curation
       - Writing - Original Draft
       - Writing - Review & Editing
       - Visualization
    - name: Marcel Reinmuth
      orcid: 0000-0002-0204-5101
      email: marcel.reinmuth@heigit.org
      role:
       - Conceptualization
       - Methodology
       - Software
       - Investigation
       - Formal analysis
       - Resources
       - Writing - Original Draft
       - Writing - Review & Editing
      affiliations:
       - name: Heidelberg Institute for Geoinformation Technology gGmbH
         address: Schloss-Wolfsbrunnenweg 33
         city: Heidelberg
         state: Germany
         postal-code: 69118
    - name: Cristian Albornoz Espinoza
      orcid: 0000-0002-5476-2508
      email: cristian.albornoz.espinoza@gmail.com
    - name: Sven Lautenbach
      orcid: 0000-0003-1825-9996
      email: sven.lautenbach@heigit.org
      affiliations:
       - name: Heidelberg Institute for Geoinformation Technology gGmbH
         address: Schloss-Wolfsbrunnenweg 33
         city: Heidelberg
         state: Germany
         postal-code: 69118
    - name: Alexander Zipf
      orcid: 0000-0003-4916-9838
      email: alexander.zipf@heigit.org
      affiliations:
       - name: Heidelberg Institute for Geoinformation Technology gGmbH
         address: Schloss-Wolfsbrunnenweg 33
         city: Heidelberg
         state: Germany
         postal-code: 69118
       - name: Institute of Geography, Heidelberg University
         address: Berliner Str. 48
         city: Heidelberg
         state: Germany
         postal-code: 69118
  date: "2025/01/01"
  page-navigation: true
  search: true
  favicon: data/figures/agile_logo-370x206.png
  sidebar:
    logo: data/figures/side-logo_v4.png
    search: true
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
       - detect_flood.qmd
       - obtain_road_network.qmd
    - part: obtain_routable_network.qmd
      chapters:
        - transform_into_graph.qmd
        - extract_difference.qmd
    - part: analyse_centrality_resilience.qmd
      chapters:
        - od.qmd
        - calculate_connectivity.qmd
        - calculate_redundancy.qmd
    - references.qmd
    - calculate_short_path.qmd
  navbar:
    right:
      - icon: filetype-pdf
        href: /data/AGILE_porto_alegre_study_latex_official_v2.pdf
        text: Paper official
      - icon: file-earmark-code-fill
        href: /data/quarto_script_rs_paper_v2.Rmd
        text: Paper rmarkdown
      - icon: github
        href: https://github.com/rruiz-s/agile-gscience-2024-rs-flood
        text: GitHub
        target: _blank
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/ricardo-r-s/
      - icon: folder
        href: https://zenodo.org/records/14662897
        text: Zenodo repository
  page-footer: 
    left: CC-By Attribution 4.0 International, HeiGIT
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

bibliography: references.bib

format:
  html:
    theme: [cosmo, styles_general.scss]
    css: styles.css
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#1b4f9d"
    code-line-numbers: true
  
  pdf:
    documentclass: scrreprt

