# Analysis Centrality and Resilience


This section describes the lane of the workflow that analyse centrality and resilience

* <span class= "font-color">**Origin-Destination matrix**</span> is the activity where we sampled Origin and Destination (OD) required to calculate the connectvity based on the edge betweenness centrality.
* We <span class="font-color">**calculate connectivity**</span> using the centrality indicator edge betweenness. A weighted sampling based on the built-up volumen on a intracity scale for each municipality and on a core metropolitan scale for the whole AoI identified urban arteries of the road network. 
* We <span class="font-color">**calculate redundancy**</span> on the hospital access using regular sampling on isochrones from each of the hospitals found in the AoI.

![Fig.1 The lane analyse centrality and resilience calculated the connectivity of the road network and the accesibility of the healthcare facilities. For the centrality, we used a weighted OD matrix based on the building density identifying the urban arteries. For the hospital accesibility, we used isochrones from ORS and a regular OD to measure the resilience component of redundancy. ](data/figures/analyse_centrality_resilience.png)

The Research Questions (RQ) asked in the introduction were the following:

* <span class="font-color">**RQ1**:</span> _"How is road connectivity affected in pre-disasteer and post-disaster scenarios based on edge betweenness centrality?"_. <br>
The centrality results, which showed the main urban arteries supported the answers given.

* <span class="font-color">**RQ2:**</span> _"Which municipalities were most affected by the flood based on the edge betweenness centrality metric?"_. <br>
The aggregation of the centrality results on both scales provided the basis for the answer to this RQ.

* <span class="font-color">**RQ3:**</span> _Which healthcare facility was less resilient in terms of lack of redundancy?_.  <br>
The comparison between three alternative paths to the hospitals' access revealed their lack of redundancy, giving the argumentation to answer this RQ.

