# Calculate redundancy

```{r}
#| eval: false
#| echo: true


library(sf)
library(DBI)
hospitals_poi <- sf::st_read(connection, Id(schema="agile_gis_2025_rs",table="hospitals_poi"))
municipalities_ghs_hospitals <- sf::st_read(connection, Id(schema="agile_gis_2025_rs",table="municipalities_ghs_hospitals"))

library(tidyverse)
hospitals_poi |> 
group_by(cd_cnes) |> 
    mutate(NAT_JUR_CAT = ifelse(NAT_JUR %in% c(3069,3999), 'Private', 'Public'),
           BEDS = sum(QTLEITP1,QTLEITP2,QTLEITP3)) |>
    ungroup() |> 
    mutate(BED_norm = (BEDS - min(BEDS)) / (max(BEDS) - min(BEDS))*3) |> 
    select(c(cd_cnes, ds_cnes, NAT_JUR, NAT_JUR_CAT, BEDS,BED_norm))

```

## RQ3

### Alternative route function

```{sql}
#| eval: false
#| echo: true


CREATE TABLE ghs_aoi_net_largest_renamed AS
SELECT 
	fid AS id,
	fromid AS source,
	toid AS target,
	weight AS cost,
	unidirectid ,
	bidirectid,
	the_geom
FROM ghs_aoi_net_largest ;

```

```{r}
#| eval: false
#| echo: true


alternative_routes <- function(df_isochrone_points){
  for (idx in 1:length(df_isochrone_points$id)) {
    tic(glue("run {idx}/{length(df_isochrone_points$id)}")) 
    hospital_name <- df_isochrone_points$cd_cnes[idx]
    origin_id <- df_isochrone_points$id[idx]
    
    table_name_1 <- glue("first_path_point_{as.character(idx)}")
    table_name_2 <- glue("second_path_point_{as.character(idx)}")
    table_name_3 <- glue("second_route_point_{as.character(idx)}")
    table_name_4 <- glue("third_path_point_{as.character(idx)}")
    table_name_5 <- glue("third_route_point_{as.character(idx)}")
    table_name_6 <- glue("three_alternative_routes_point_{as.character(idx)}")
    table_name_7 <- glue("table_end_point_{as.character(idx)}")
    
#### First shortest path
dbExecute(glue_sql("DROP TABLE IF EXISTS {`table_name_1`}", .con=connection),
          conn=connection)  
query_1 <- glue_sql("
CREATE TABLE {`table_name_1`} AS
SELECT
        seq,
        path.start_vid,
        path.end_vid,
        path.node,
        path.edge,
        net.the_geom,
        path.cost,
        path.agg_cost,
        1 AS path
  FROM pgr_dijkstra('
        SELECT
            id,
            source,
            target,
            cost
        FROM ghs_aoi_net_largest_renamed',
                    ARRAY(SELECT id FROM regular_sampling_isochrones_snapped_ghs_aoi WHERE id ={origin_id}),
                    ARRAY(SELECT id AS end_id FROM municipalities_ghs_hospitals WHERE cd_cnes = {hospital_name}),
                    directed:=TRUE) AS path
LEFT JOIN ghs_aoi_net_largest_renamed AS net
ON path.edge = net.id", .con = connection)
# Send the query
result_q1 <- dbGetQuery(conn= connection, query_1)

#### Second network for second shortest path
dbExecute(glue_sql("DROP TABLE IF EXISTS {`table_name_2`}", .con=connection),
          conn=connection)  
query_2 <- glue_sql("CREATE TABLE {`table_name_2`} AS 
   SELECT 	net.id,
            net.source,
            net.target,
            route.edge,
            route.cost AS cost,
            net.the_geom,
            CASE 
                WHEN route.node = net.source 
                OR route.node = net.target THEN net.cost * 20
                ELSE net.cost
            END AS cost_updated_st
            FROM            
                ghs_aoi_net_largest_renamed AS net
            LEFT JOIN 
                {`table_name_1`}  AS route 
            ON  
                route.edge= net.id", .con = connection);
result_q2 <- dbGetQuery(conn= connection, query_2)

#### Second shortest path
dbExecute(glue_sql("DROP TABLE IF EXISTS {`table_name_3`}", .con=connection),
          conn=connection)  
query_3 <- glue_sql("
CREATE TABLE {`table_name_3`} AS
SELECT 
    seq,
        shortest.node,
        shortest.edge,
        net.the_geom,
	net.cost_updated_st,
	        shortest.start_vid,
        shortest.end_vid,
    2 AS path
    FROM 
    pgr_dijkstra('
        SELECT
            id,
            source,
            target,
            cost_updated_st AS cost
        FROM
            {`table_name_2`}',
        ARRAY(SELECT id FROM regular_sampling_isochrones_snapped_ghs_aoi WHERE id = {origin_id}),
        ARRAY(SELECT id FROM municipalities_ghs_hospitals WHERE cd_cnes = {hospital_name}),
        directed:=TRUE
    ) AS shortest
LEFT JOIN
    {`table_name_2`} AS net 
    ON shortest.edge = net.id;
", .con = connection)
dbExecute(conn = connection, query_3)  
#### Third network for third shortest path
dbExecute(glue_sql("DROP TABLE IF EXISTS {`table_name_4`}", .con=connection),
          conn=connection)  
query_4 <- glue_sql("
CREATE TABLE {`table_name_4`} AS 
   SELECT 	net.id,
            net.source,
            net.target,
            route.edge,
            route.cost_updated_st,
            net.cost,
            net.the_geom,
            CASE 
                WHEN route.node = net.source 
                OR route.node = net.target THEN net.cost_updated_st * 20
                ELSE net.cost_updated_st
            END AS cost_updated_nd
            FROM            
                {`table_name_2`} AS net
            LEFT JOIN 
                {`table_name_3`}  AS route 
            ON  
                route.edge= net.id", .con=connection);
dbExecute(conn = connection, query_4)  
#### Third shortest path
dbExecute(glue_sql("DROP TABLE IF EXISTS {`table_name_5`}", .con=connection),
          conn=connection)  
query_5 <- glue_sql ("CREATE TABLE {`table_name_5`} AS
SELECT 
    seq,
        shortest.node,
        shortest.edge,
        net.the_geom,
	net.cost_updated_st,
	        shortest.start_vid,
        shortest.end_vid,
    3 AS path
FROM 
	pgr_dijkstra('
					SELECT id,
					        source,
					        target,
					        cost_updated_nd AS cost 
					FROM {`table_name_4`}',
        ARRAY(SELECT id FROM regular_sampling_isochrones_snapped_ghs_aoi WHERE id = {origin_id}),
        ARRAY(SELECT id FROM municipalities_ghs_hospitals WHERE cd_cnes = {hospital_name}),
                directed:= true) AS shortest
LEFT JOIN
	{`table_name_4`} AS net ON net.id = shortest.edge", .con=connection);                

dbExecute(conn = connection, query_5)  

dbExecute(glue_sql("DROP TABLE IF EXISTS {`table_name_6`}", .con=connection),
          conn=connection)  

alterantive_point_1 <- glue_sql("
CREATE TABLE {`table_name_6`} AS 
SELECT start_vid, end_vid,path, the_geom, edge FROM {`table_name_1`}
UNION
SELECT start_vid, end_vid,path, the_geom, edge FROM {`table_name_3`}
UNION
SELECT start_vid, end_vid,path, the_geom, edge FROM {`table_name_5`}", .con = connection)

result_6 <- dbGetQuery(conn = connection, alterantive_point_1)

dbExecute(glue_sql("DROP TABLE IF EXISTS {`table_name_7`}", .con=connection),
          conn=connection)  
table_end_point_1 <- glue_sql("
CREATE TABLE {`table_name_7`} AS
SELECT
            alternative.*,
            ceil(st_length(alternative.the_geom::geography)/1000) As length,
            original.cost AS cost
          FROM
            {`table_name_6`} AS alternative
          LEFT JOIN
           ghs_aoi_net_largest_renamed  AS original
          ON
          alternative.edge = original.id
          WHERE
            edge!= -1", .con=connection)
result_7 <- dbGetQuery(conn=connection,table_end_point_1 )


calculations <- glue_sql("
  INSERT INTO table_end_v2 (start_vid, end_vid, path, length, cost, the_geom)
        SELECT 
          start_vid,
          end_vid,
          path,
          sum(length) AS length,
          sum(cost) AS cost,
          st_union(the_geom) as the_geom
        FROM 
            {`table_name_7`} 
        GROUP BY
        start_vid,
        end_vid,
        path
        ORDER BY path ASC", .con=connection)

dbExecute(conn=connection, calculations)
toc() 
}
}
```
### Prepare for war: creating index

```{sql}
#| eval: false
#| echo: true


---- creating indexes public
--- ghs_aoi_net_largest_renamed
CREATE INDEX idx_ghs_aoi_net_largest_renamed ON public.ghs_aoi_net_largest_renamed USING gist(the_geom);
CREATE INDEX idx_ghs_aoi_net_largest_renamed_source ON public.ghs_aoi_net_largest_renamed USING btree(source);
CREATE INDEX idx_ghs_aoi_net_largest_renamed_target ON public.ghs_aoi_net_largest_renamed USING btree(target);
CREATE INDEX idx_ghs_aoi_net_largest_renamed_id ON public.ghs_aoi_net_largest_renamed USING btree(id);
--- ghs_aoi_net_largest_vertices_pgr
CREATE INDEX idx_ghs_aoi_net_largest_vertices_pgr ON public.ghs_aoi_net_largest_renamed_vertices_pgr USING gist(the_geom);
CREATE INDEX idx_ghs_aoi_net_largest_vertices_id ON public.ghs_aoi_net_largest_renamed_vertices_pgr USING btree(id);
--- hospitals_poi
CREATE INDEX idx_municipalities_ghs_hospitals_id ON public.municipalities_ghs_hospitals USING btree(id);

```

### Create table using the function

```{r}
#| echo: true
#| eval: false

library(glue)
library(tictoc)
table_end_v2 <- glue_sql("CREATE TABLE table_end_v2
                (start_vid integer,
                end_vid integer,
                path smallint,
                length float,
                cost float,
                the_geom geometry)")
table_end_db <- dbGetQuery(conn=connection,table_end_v2 )

isochrones_sampling_points <-st_read(connection, Id(schema="agile_gis_2025_rs", table="regular_sampling_isochrones_snapped_ghs_aoi"))
df_isochrone_points  <- isochrones_sampling_points 

for (idx_hospital in 1:length(unique(isochrones_sampling_points$cd_cnes))){
  tic(glue("hospital run {idx_hospital}/{length(unique(isochrones_sampling_points$cd_cnes))}"))
  code_hospital<-unique(isochrones_sampling_points$cd_cnes)[idx_hospital]
  points_for_isochrone <- filter(isochrones_sampling_points,
                                 cd_cnes == code_hospital)
  alternative_routes(
    df_isochrone_points=points_for_isochrone)
  toc()
}

```


Work in progress, waiting for acceptance.
